# المرحلة الأولى: إعداد بيئة العمل

في هذه الخطوة سنقوم بالآتي:
1. استدعاء المكتبات الأساسية للتعامل مع البيانات
2. التجهيز للاتصال بقاعدة بيانات المصدر اسكيول لايت وقاعدة بيانات  الهدف بوستجر اسكيول
3. التركيز على استخراج الجداول الخاصة بالمبيعات المنتجات العملاء والتوصيل للإجابة على أسئلة العمل

In [1]:
import sqlite3
import pandas as pd
from sqlalchemy import create_engine , text
import datetime
import matplotlib.pyplot as plt

SQLITE_DB = 'olist.sqlite'
conn_string = 'postgresql://postgres:kenan123@localhost:5432/finall_dwh'

In [2]:
def get_table_names(db_path):
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = cursor.fetchall()
        
        conn.close()
        
        print("الجداول الموجودة في قاعدة البيانات هي:")
        for table in tables:
            print(f"- {table[0]}")
            
    except Exception as e:
        print(f"حدث خطأ أثناء محاولة قراءة أسماء الجداول: {e}")

# قم بتمرير مسار ملفك هنا للتأكد
get_table_names(SQLITE_DB)

الجداول الموجودة في قاعدة البيانات هي:
- product_category_name_translation
- sellers
- customers
- geolocation
- order_items
- order_payments
- order_reviews
- orders
- products
- leads_qualified
- leads_closed

# تابع المرحلة الأولى: استخراج البيانات

In [3]:


def extract_data(db_path):
    try:
        src_conn = sqlite3.connect(db_path)
        
        data = {
            'orders': pd.read_sql("SELECT * FROM orders", src_conn),
            'order_items': pd.read_sql("SELECT * FROM order_items", src_conn),
            'products': pd.read_sql("SELECT * FROM products", src_conn),
            'customers': pd.read_sql("SELECT * FROM customers", src_conn),
            'sellers': pd.read_sql("SELECT * FROM sellers", src_conn),
            'translations': pd.read_sql("SELECT * FROM product_category_name_translation", src_conn)
        }
        
        src_conn.close()
        print("تم سحب البيانات")
        return data
    
    except Exception as e:
        print(f"خطا: {e}")
        return None

raw_data = extract_data(SQLITE_DB)

تم سحب البيانات

# تابع المرحلة الأولى: فحص عدد الجداول و الاعمدة

In [4]:
try:
    if raw_data:
        for table_name, df in raw_data.items():
            print(f" الجدول: {table_name}")
            print(f"الأعمدة: {df.columns.tolist()}")
            print("-" * 80)
    else:
        print("البيانات غير متوفره")
except Exception as e:
    print(f"خطا: {e}")

 الجدول: orders
الأعمدة: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
--------------------------------------------------------------------------------
 الجدول: order_items
الأعمدة: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
--------------------------------------------------------------------------------
 الجدول: products
الأعمدة: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
--------------------------------------------------------------------------------
 الجدول: customers
الأعمدة: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
--------------------------------------------------------------------------------
 الجدول: sellers
الأعمدة: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
--------------------------------------------------------------------------------
 الجدول: translations
الأعمدة: ['product_category_name', 'product_category_name_english']
--------------------------------------------------------------------------------

----------------------------------------------------------------

# المرحلة الثانية: تصفية الأعمدة

بعد استكشاف البيانات الخام، تبين أن معظم الأعمدة ضرورية للإجابة على أسئلة العمل، باستثناء بعض الأعمدة في جدول المنتجات التي لا تضيف قيمة للتحليل وتستهلك الذاكرة

**الهدف من هذه المرحلة:**
1. الإبقاء على الجداول والأعمدة الأساسية كما هي
2. تقليل حجم البيانات في جدول المنتجات بحذف الأعمدة غير الضرورية وهي:
   - طول اسم المنتج
   - طول وصف المنتج
   - عدد صور المنتج

In [5]:
def select_relevant_columns(data):
    try:
        unnecessary_product_cols = [
            'product_name_lenght', 
            'product_description_lenght', 
            'product_photos_qty'
        ]
        
        if 'products' in data:
            data['products'] = data['products'].drop(columns=unnecessary_product_cols, errors='ignore')
            print("تم التصفيه")
        else:
            print("جدول المنتجات غير موجود")
            
        return data

    except Exception as e:
        print(f"خطا {e}")
        return data

raw_data = select_relevant_columns(raw_data)

تم التصفيه

---------------------------------------------

# المرحلة الثالثة: فحص وتقييم جودة البيانات

في هذه المرحلة ساقوم ببناء فانكشن فحص شاملة تمر على جميع الجداول التي استخرجتها لتزويدي بتقرير مفصل

**ما الذي سيظهره لنا هذا التقرير لكل جدول؟**
1. **الإحصائيات العامة:** عدد  الصفوف وعدد  الأعمدة
2. **القيم المفقودة:** سنعرف بالضبط كم عدد الخلايا الفارغة في كل عمود وما هي نسبتها المئوية من إجمالي البيانات
3. **البيانات المكررة:** سنكشف إذا كان هناك صفوف متطابقة تماماً تحتاج إلى حذف لضمان دقة التقارير المالية
4. **أنواع البيانات:** التأكد من أن التواريخ والأرقام مخزنة بصيغتها الصحيحة وليس كنصوص
5. **القيم الفريدة:** معرفة عدد القيم غير المتكررة في كل عمود وهو أمر ضروري للتأكد من صحة المفاتيح الأساسية

In [6]:
def generate_data_quality_report(data):
    try:
        if not data:
            print("لا توجد بيانات")
            return

        for table_name, df in data.items():
            print(f"\n{'='*30}")
            print(f"تقرير جوده البيانات: {table_name}")
            print(f"{'='*30}")


            rows, cols = df.shape
            print(f"- اجمالي عدد السجلات: {rows}")
            print(f"- اجمالي عدد الأعمدة: {cols}")

            duplicate_count = df.duplicated().sum()
            print(f"- عدد السجلات المكررة بالكامل: {duplicate_count}")

            print("\n تحليل تفصيلي للأعمدة:")
            
            analysis = pd.DataFrame({
                'نوع البيانات': df.dtypes,
                'القيم المفقودة': df.isnull().sum(),
                'النسبة المئوية للمفقود': (df.isnull().sum() / rows * 100).round(2).astype(str) + '%',
                'القيم الفريدة': df.nunique()
            })
            
            print(analysis)
            print("\n" + "-"*50)

    except Exception as e:
        print(f"خطا: {e}")

generate_data_quality_report(raw_data)

==============================
تقرير جوده البيانات: orders
==============================
- اجمالي عدد السجلات: 99441
- اجمالي عدد الأعمدة: 8
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                              نوع البيانات  القيم المفقودة  \
order_id                            object               0
customer_id                         object               0
order_status                        object               0
order_purchase_timestamp            object               0
order_approved_at                   object             160
order_delivered_carrier_date        object            1783
order_delivered_customer_date       object            2965
order_estimated_delivery_date       object               0

                              النسبة المئوية للمفقود  القيم الفريدة
order_id                                        0.0%          99441
customer_id                                     0.0%          99441
order_status                                    0.0%              8
order_purchase_timestamp                        0.0%          98875
order_approved_at                              0.16%          90733
order_delivered_carrier_date                   1.79%          81018
order_delivered_customer_date                  2.98%          95664
order_estimated_delivery_date                   0.0%            459

--------------------------------------------------

==============================
تقرير جوده البيانات: order_items
==============================
- اجمالي عدد السجلات: 112650
- اجمالي عدد الأعمدة: 7
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                    نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
order_id                  object               0                   0.0%
order_item_id              int64               0                   0.0%
product_id                object               0                   0.0%
seller_id                 object               0                   0.0%
shipping_limit_date       object               0                   0.0%
price                    float64               0                   0.0%
freight_value            float64               0                   0.0%

                     القيم الفريدة
order_id                     98666
order_item_id                   21
product_id                   32951
seller_id                     3095
shipping_limit_date          93318
price                         5968
freight_value                 6999

--------------------------------------------------

==============================
تقرير جوده البيانات: products
==============================
- اجمالي عدد السجلات: 32951
- اجمالي عدد الأعمدة: 6
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                      نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
product_id                  object               0                   0.0%
product_category_name       object             610                  1.85%
product_weight_g           float64               2                  0.01%
product_length_cm          float64               2                  0.01%
product_height_cm          float64               2                  0.01%
product_width_cm           float64               2                  0.01%

                       القيم الفريدة
product_id                     32951
product_category_name             73
product_weight_g                2204
product_length_cm                 99
product_height_cm                102
product_width_cm                  95

--------------------------------------------------

==============================
تقرير جوده البيانات: customers
==============================
- اجمالي عدد السجلات: 99441
- اجمالي عدد الأعمدة: 5
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                         نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
customer_id                    object               0                   0.0%
customer_unique_id             object               0                   0.0%
customer_zip_code_prefix        int64               0                   0.0%
customer_city                  object               0                   0.0%
customer_state                 object               0                   0.0%

                          القيم الفريدة
customer_id                       99441
customer_unique_id                96096
customer_zip_code_prefix          14994
customer_city                      4119
customer_state                       27

--------------------------------------------------

==============================
تقرير جوده البيانات: sellers
==============================
- اجمالي عدد السجلات: 3095
- اجمالي عدد الأعمدة: 4
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                       نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
seller_id                    object               0                   0.0%
seller_zip_code_prefix        int64               0                   0.0%
seller_city                  object               0                   0.0%
seller_state                 object               0                   0.0%

                        القيم الفريدة
seller_id                        3095
seller_zip_code_prefix           2246
seller_city                       611
seller_state                       23

--------------------------------------------------

==============================
تقرير جوده البيانات: translations
==============================
- اجمالي عدد السجلات: 71
- اجمالي عدد الأعمدة: 2
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                              نوع البيانات  القيم المفقودة  \
product_category_name               object               0
product_category_name_english       object               0

                              النسبة المئوية للمفقود  القيم الفريدة
product_category_name                           0.0%             71
product_category_name_english                   0.0%             71

--------------------------------------------------

-------------------------

# المرحلة الرابعة: معالجة أنواع التواريخ

في هذه الخطوة، سنقوم بمعالجة المشكلة الأولى التي كشفها التقرير وهي تحويل أعمدة التواريخ من نصوص إلى صيغة زمنية صحيحة

In [7]:
def convert_to_datetime(data):

    try:
        order_dates = [
            'order_purchase_timestamp', 
            'order_approved_at',
            'order_delivered_carrier_date', 
            'order_delivered_customer_date',
            'order_estimated_delivery_date'
        ]
        
        if 'orders' in data:
            for col in order_dates:
                data['orders'][col] = pd.to_datetime(data['orders'][col], errors='coerce')
            print("تم تحويل تواريخ الطلبات بنجاح")

        if 'order_items' in data:
            data['order_items']['shipping_limit_date'] = pd.to_datetime(data['order_items']['shipping_limit_date'], errors='coerce')
            print("تم تحويل تاريخ شحن المنتجات بنجاح")
            
        return data

    except Exception as e:
        print(f"خطا: {e}")
        return data

raw_data = convert_to_datetime(raw_data)

تم تحويل تواريخ الطلبات بنجاح
تم تحويل تاريخ شحن المنتجات بنجاح

-----------------------

# المرحلة الخامسة: معالجة القيم المفقودة للأوزان والأبعاد

في هذه الخطوة ساقوم بمعالجة النقص في بيانات جدول المنتجات تحديدا الوزن الطول العرض والارتفاع

**آلية العمل:**
لضمان الدقة العالية بدلا من وضع أرقام عشوائية ساقوم بحساب "المتوسط الحسابي" للأوزان والأبعاد لكل فئة من فئات المنتجات على حدة ثم ساقوم بتعبئة الفراغات في المنتجات المفقودة بناء على متوسط الفئة التي تنتمي إليها وفي حال فشل ذلك مثلا إذا كانت الفئة نفسها مفقودة ساستخدم المتوسط العام للمنتجات كحل أخير لتجنب تعطل البيانات

In [8]:
def fill_missing_dimensions(data):
    try:
        if 'products' in data:
            df = data['products']
            
            dimension_cols = [
                'product_weight_g', 
                'product_length_cm', 
                'product_height_cm', 
                'product_width_cm'
            ]
            
            for col in dimension_cols:
                df[col] = df.groupby('product_category_name')[col].transform(lambda x: x.fillna(x.mean()))
                
                df[col] = df[col].fillna(df[col].mean())
                
            data['products'] = df
            print("تمت معالجه القيم المفقوده")
            
        return data

    except Exception as e:
        print(f"خطا: {e}")
        return data

raw_data = fill_missing_dimensions(raw_data)

تمت معالجه القيم المفقوده

--------------------------------------------

# المرحلة السادسة: معالجة فئات المنتجات المفقودة

في هذه الخطوة ساقوم بحل مشكلة المنتجات التي لا تنتمي لاي قسم وتلك التي ليس لها ترجمة مقابلة

**آلية العمل:**
ساقوم بالبحث عن أي خلايا فارغة في عمود تصنيف المنتجات ونستبدلها بكلمة تعني "غير محدد" بعد ذلك ساقوم بإضافة هذا التصنيف الجديد إلى جدول الترجمات لضمان التعرف عليه باللغة الإنجليزية في التقرير النهائي هذا الإجراء يضمن أن جميع المبيعات المرتبطة بهذه المنتجات سيتم حسابها بدقة ضمن الأرباح ولن يتم تجاهلها أو حذفها

In [9]:
def handle_missing_categories(data):

    try:
        unknown_label_pt = 'desconhecido'
        unknown_label_en = 'Unknown'
        
        if 'products' in data:
            data['products']['product_category_name'] = data['products']['product_category_name'].fillna(unknown_label_pt)
            print("تم معالجة التصنيفات المفقوده")
            
        if 'translations' in data:
            if not (data['translations']['product_category_name'] == unknown_label_pt).any():
                new_translation = pd.DataFrame({
                    'product_category_name': [unknown_label_pt],
                    'product_category_name_english': [unknown_label_en]
                })
                data['translations'] = pd.concat([data['translations'], new_translation], ignore_index=True)
            print("تم تحديث جدول الترجمات")
            
        return data

    except Exception as e:
        print(f"خطا: {e}")
        return data

raw_data = handle_missing_categories(raw_data)

تم معالجة التصنيفات المفقوده
تم تحديث جدول الترجمات

--------------------------------------

# المرحلة السابعة: التحقق من جودة البيانات 

بعد تطبيق عمليات التنظيف ساقوم بإعادة تشغيل تقرير جودة البيانات للتأكد من:
1. اختفاء القيم المفقودة من جدول المنتجات
2. إضافة الفئة الجديدة لجدول الترجمات
3. تحويل أنواع بيانات التواريخ 
4. بالنسبه للطلبات لن اقوم بعمل اي تعديل عليها لانه قد يكون هناك طلبات لم تصل بعد لذلك تظهر القيمه نال لذلك لن اقوم بعمل اي تغير في الطلبات

In [10]:
print("يتم الفحص")
generate_data_quality_report(raw_data)

يتم الفحص

==============================
تقرير جوده البيانات: orders
==============================
- اجمالي عدد السجلات: 99441
- اجمالي عدد الأعمدة: 8
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                                 نوع البيانات  القيم المفقودة  \
order_id                               object               0
customer_id                            object               0
order_status                           object               0
order_purchase_timestamp       datetime64[ns]               0
order_approved_at              datetime64[ns]             160
order_delivered_carrier_date   datetime64[ns]            1783
order_delivered_customer_date  datetime64[ns]            2965
order_estimated_delivery_date  datetime64[ns]               0

                              النسبة المئوية للمفقود  القيم الفريدة
order_id                                        0.0%          99441
customer_id                                     0.0%          99441
order_status                                    0.0%              8
order_purchase_timestamp                        0.0%          98875
order_approved_at                              0.16%          90733
order_delivered_carrier_date                   1.79%          81018
order_delivered_customer_date                  2.98%          95664
order_estimated_delivery_date                   0.0%            459

--------------------------------------------------

==============================
تقرير جوده البيانات: order_items
==============================
- اجمالي عدد السجلات: 112650
- اجمالي عدد الأعمدة: 7
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                       نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
order_id                     object               0                   0.0%
order_item_id                 int64               0                   0.0%
product_id                   object               0                   0.0%
seller_id                    object               0                   0.0%
shipping_limit_date  datetime64[ns]               0                   0.0%
price                       float64               0                   0.0%
freight_value               float64               0                   0.0%

                     القيم الفريدة
order_id                     98666
order_item_id                   21
product_id                   32951
seller_id                     3095
shipping_limit_date          93318
price                         5968
freight_value                 6999

--------------------------------------------------

==============================
تقرير جوده البيانات: products
==============================
- اجمالي عدد السجلات: 32951
- اجمالي عدد الأعمدة: 6
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                      نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
product_id                  object               0                   0.0%
product_category_name       object               0                   0.0%
product_weight_g           float64               0                   0.0%
product_length_cm          float64               0                   0.0%
product_height_cm          float64               0                   0.0%
product_width_cm           float64               0                   0.0%

                       القيم الفريدة
product_id                     32951
product_category_name             74
product_weight_g                2204
product_length_cm                101
product_height_cm                104
product_width_cm                  97

--------------------------------------------------

==============================
تقرير جوده البيانات: customers
==============================
- اجمالي عدد السجلات: 99441
- اجمالي عدد الأعمدة: 5
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                         نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
customer_id                    object               0                   0.0%
customer_unique_id             object               0                   0.0%
customer_zip_code_prefix        int64               0                   0.0%
customer_city                  object               0                   0.0%
customer_state                 object               0                   0.0%

                          القيم الفريدة
customer_id                       99441
customer_unique_id                96096
customer_zip_code_prefix          14994
customer_city                      4119
customer_state                       27

--------------------------------------------------

==============================
تقرير جوده البيانات: sellers
==============================
- اجمالي عدد السجلات: 3095
- اجمالي عدد الأعمدة: 4
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                       نوع البيانات  القيم المفقودة النسبة المئوية للمفقود  \
seller_id                    object               0                   0.0%
seller_zip_code_prefix        int64               0                   0.0%
seller_city                  object               0                   0.0%
seller_state                 object               0                   0.0%

                        القيم الفريدة
seller_id                        3095
seller_zip_code_prefix           2246
seller_city                       611
seller_state                       23

--------------------------------------------------

==============================
تقرير جوده البيانات: translations
==============================
- اجمالي عدد السجلات: 72
- اجمالي عدد الأعمدة: 2
- عدد السجلات المكررة بالكامل: 0

 تحليل تفصيلي للأعمدة:
                              نوع البيانات  القيم المفقودة  \
product_category_name               object               0
product_category_name_english       object               0

                              النسبة المئوية للمفقود  القيم الفريدة
product_category_name                           0.0%             72
product_category_name_english                   0.0%             72

--------------------------------------------------

---------------------------

# المرحلة الثامنه: بناء جدول أبعاد الزمن

يعتبر هذا الجدول العمود الفقري لأي تحليل زمني بدلاً من الاعتماد على تاريخ واحد فقط سنقوم بتوليد جدول يحتوي على تفاصيل كاملة لكل يوم يقع ضمن نطاق بياناتنا

**المميزات التي سنضيفها:**
1. **الشمولية:** استخراج السنة الربع السنوي الشهر واسم اليوم
2. **تسهيل التقارير:** إضافة أعمدة تساعد في الإجابة على سؤال "اتجاه المبيعات عبر الزمن" دون الحاجة لعمليات حسابية معقدة أثناء عرض التقارير
3. **المفتاح البديل:** إنشاء مفتاح رقمي فريد يسهل ربط هذا الجدول بجداول الحقائق لاحقاً

In [11]:
def create_dim_date(data):

    try:
        if 'orders' in data:
            min_date = data['orders']['order_purchase_timestamp'].min().date()
            max_date = data['orders']['order_purchase_timestamp'].max().date()
            
            date_range = pd.date_range(start=min_date, end=max_date)
            
            dim_date = pd.DataFrame({'full_date': date_range})
            
            dim_date['date_key'] = dim_date['full_date'].dt.strftime('%Y%m%d').astype(int)
            dim_date['year'] = dim_date['full_date'].dt.year
            dim_date['quarter'] = dim_date['full_date'].dt.quarter
            dim_date['month'] = dim_date['full_date'].dt.month
            dim_date['day_of_week'] = dim_date['full_date'].dt.day_name()
            dim_date['is_weekend'] = dim_date['full_date'].dt.dayofweek.isin([5, 6]).astype(int)
            
            print(f" تم انشاء جدول بعد الزمن")
            return dim_date
    except Exception as e:
        print(f"خطا: {e}")
        return None

dim_date = create_dim_date(raw_data)

 تم انشاء جدول بعد الزمن

-----------------------------

# المرحلة التاسعه: بناء جداول الأبعاد الأساسية وتجهيز نظام تتبع التغيرات SCD Type 2

ساقوم الآن ببناء جداول الأبعاد للعملاء المنتجات البائعين والطلبات في هذه المرحلة سنطبق القواعد الهندسية الصارمة التي اتفقنا عليها

**ما ساقوم بتنفيذه:**
1. **المفاتيح البديلة:** ساقوم بانشاء معرفات رقمية بسيطة (تبدأ من 1) لكل سجل لتسريع عمليات الربط في مستودع البيانات
2. **نظام تتبع التغيرات التاريخية:** ساضيف أعمدة تاريخ البداية تاريخ النهاية وحالة السجل الحالية
   - بما أن هذه هي النسخة الأولى من البيانات، سنعتبر جميع السجلات الحالية هي النسخة النشطة
3. **تجهيز البيانات للتحليل:** دمج أسماء الفئات المترجمة داخل جدول أبعاد المنتجات ليكون التقرير جاهزاً باللغة الإنجليزية مباشرة

In [12]:

def build_dimensions(data):

    dimensions = {}
    current_time = datetime.datetime.now()
    
    try:
        if 'customers' in data:
            dim_customer = data['customers'].copy()
            dim_customer.insert(0, 'customer_key', range(1, len(dim_customer) + 1))

            dim_customer['start_date'] = current_time
            dim_customer['end_date'] = pd.NA
            dim_customer['is_current'] = 1
            dimensions['dim_customer'] = dim_customer


        if 'products' in data and 'translations' in data:
            dim_product = pd.merge(data['products'], data['translations'], on='product_category_name', how='left')
            dim_product.insert(0, 'product_key', range(1, len(dim_product) + 1))
            dim_product['start_date'] = current_time
            dim_product['end_date'] = pd.NA
            dim_product['is_current'] = 1
            dimensions['dim_product'] = dim_product


        if 'sellers' in data:
            dim_seller = data['sellers'].copy()
            dim_seller.insert(0, 'seller_key', range(1, len(dim_seller) + 1))
            dim_seller['start_date'] = current_time
            dim_seller['end_date'] = pd.NA
            dim_seller['is_current'] = 1
            dimensions['dim_seller'] = dim_seller


        if 'orders' in data:

            dim_order = data['orders'][['order_id', 'order_status']].drop_duplicates().copy()
            dim_order.insert(0, 'order_key', range(1, len(dim_order) + 1))
            dim_order['start_date'] = current_time
            dim_order['end_date'] = pd.NA
            dim_order['is_current'] = 1
            dimensions['dim_order'] = dim_order

        print("تم بناء جميع جداول الأبعاد مع المفاتيح البديلة ونظام تتبع التغيرات")
        return dimensions

    except Exception as e:
        print(f"خطا {e}")
        return None

all_dimensions = build_dimensions(raw_data)

تم بناء جميع جداول الأبعاد مع المفاتيح البديلة ونظام تتبع التغيرات

-------------------------------------------------

# المرحلة العاشرة: بناء جدول حقائق المبيعات

هذا الجدول هو المسؤول عن الإجابة على الأسئلة المالية: ما هي اتجاهات المبيعات؟ و من هم أفضل العملاء والمنتجات؟

In [13]:
def build_fact_order_items(raw_data, dimensions):

    try:
        fact_df = pd.merge(
            raw_data['order_items'], 
            raw_data['orders'][['order_id', 'customer_id', 'order_purchase_timestamp']], 
            on='order_id', 
            how='inner'
        )


        fact_df = pd.merge(fact_df, dimensions['dim_customer'][['customer_id', 'customer_key']], on='customer_id', how='inner')


        fact_df = pd.merge(fact_df, dimensions['dim_product'][['product_id', 'product_key']], on='product_id', how='inner')


        fact_df = pd.merge(fact_df, dimensions['dim_seller'][['seller_id', 'seller_key']], on='seller_id', how='inner')


        fact_df = pd.merge(fact_df, dimensions['dim_order'][['order_id', 'order_key']], on='order_id', how='inner')


        fact_df['date_key'] = fact_df['order_purchase_timestamp'].dt.strftime('%Y%m%d').astype(int)


        final_fact = fact_df[[
            'order_key', 'customer_key', 'product_key', 'seller_key', 'date_key',
            'price', 'freight_value', 'order_item_id'
        ]].copy()

        final_fact.rename(columns={
            'price': 'sales_amount',
            'freight_value': 'freight_amount',
            'order_item_id': 'quantity'
        }, inplace=True)

        print(f"تم بناء جدول الفاكت اوردر")
        return final_fact

    except Exception as e:
        print(f"خطا: {e}")
        return None

fact_order_items = build_fact_order_items(raw_data, all_dimensions)

تم بناء جدول الفاكت اوردر

---------------------------

# المرحلة الحادي عشرة: بناء جدول حقائق أداء التوصيل

في هذه الخطوة، سنقوم بتحويل التواريخ المعقدة إلى مقاييس رقمية سهلة القراءة عدد الأيام

**المقاييس التي سنقوم بحسابها:**
1. **مدة التوصيل الفعلية :** الفرق بين تاريخ الشراء وتاريخ وصول الطلب للعميل
2. **أيام التأخير :** الفرق بين التاريخ المتوقع والتاريخ الفعلي إذا وصل الطلب بعد موعده
3. **تأخير الموافقة :** الوقت المستغرق للموافقة على الطلب بعد شرائه
4. **تأخير الشحن :** الوقت المستغرق لتسليم الطلب لشركة الشحن بعد الموافقة عليه

سيتم ربط هذه الأرقام بكافة الأبعاد العميل المنتج البائع والوقت لمعرفة أي ولاية أو أي فئة منتجات هي الأكثر تأخراً

In [14]:
def build_fact_delivery_performance(raw_data, dimensions):

    try:
        delivered_orders = raw_data['orders'][raw_data['orders']['order_status'] == 'delivered'].copy()
        
        fact_df = pd.merge(
            delivered_orders,
            raw_data['order_items'][['order_id', 'product_id', 'seller_id']],
            on='order_id',
            how='inner'
        )


        fact_df['delivery_days'] = (fact_df['order_delivered_customer_date'] - fact_df['order_purchase_timestamp']).dt.days
        

        fact_df['late_days'] = (fact_df['order_delivered_customer_date'] - fact_df['order_estimated_delivery_date']).dt.days
        fact_df['late_days'] = fact_df['late_days'].apply(lambda x: x if x > 0 else 0)
        
        fact_df['approval_delay'] = (fact_df['order_approved_at'] - fact_df['order_purchase_timestamp']).dt.days
        fact_df['carrier_delay'] = (fact_df['order_delivered_carrier_date'] - fact_df['order_approved_at']).dt.days


        fact_df = pd.merge(fact_df, dimensions['dim_customer'][['customer_id', 'customer_key']], on='customer_id', how='inner')
        fact_df = pd.merge(fact_df, dimensions['dim_product'][['product_id', 'product_key']], on='product_id', how='inner')
        fact_df = pd.merge(fact_df, dimensions['dim_seller'][['seller_id', 'seller_key']], on='seller_id', how='inner')
        fact_df = pd.merge(fact_df, dimensions['dim_order'][['order_id', 'order_key']], on='order_id', how='inner')


        fact_df['date_key'] = fact_df['order_purchase_timestamp'].dt.strftime('%Y%m%d').astype(int)


        final_fact = fact_df[[
            'customer_key', 'seller_key', 'product_key', 'order_key', 'date_key',
            'delivery_days', 'late_days', 'approval_delay', 'carrier_delay'
        ]].copy()


        final_fact = final_fact.fillna(0)

        print(f"تم بناء جداول الفاكت ديليفري")
        return final_fact

    except Exception as e:
        print(f"خطا: {e}")
        return None

fact_delivery = build_fact_delivery_performance(raw_data, all_dimensions)

تم بناء جداول الفاكت ديليفري

--------------------------------------

# المرحلة الثانية عشرة: تحميل البيانات إلى بوستجر وإعداد الروابط

في هذه الخطوة النهائية، سنقوم بالآتي:
1. **إنشاء الاتصال:** الربط مع قاعدة بيانات بوستجر
2. **رفع الجداول:** إرسال جداول الأبعاد والحقائق من ذاكرة البرنامج إلى قاعدة البيانات
3. **تعريف المفاتيح :** إخبار قاعدة البيانات بأن هذه الجداول مرتبطة ببعضها (لإظهار الخطوط في الرسمة).
4. **الفهرسة :** إضافة فهارس على مفاتيح الربط لتسريع التقارير

In [15]:
def load_to_postgres(all_dims, fact_sales, fact_delivery, dim_date, conn_str):

    try:

        engine = create_engine(conn_str)

        dim_date.to_sql('dim_date', engine, if_exists='replace', index=False)
        

        for name, df in all_dims.items():
            df.to_sql(name, engine, if_exists='replace', index=False)
        

        fact_sales.to_sql('fact_order_items', engine, if_exists='replace', index=False)
        fact_delivery.to_sql('fact_delivery_performance', engine, if_exists='replace', index=False)
        
        print("تم رفع البيانات")


        with engine.connect() as con:

            con.execute(text("ALTER TABLE dim_customer ADD PRIMARY KEY (customer_key);"))
            con.execute(text("ALTER TABLE dim_product ADD PRIMARY KEY (product_key);"))
            con.execute(text("ALTER TABLE dim_seller ADD PRIMARY KEY (seller_key);"))
            con.execute(text("ALTER TABLE dim_order ADD PRIMARY KEY (order_key);"))
            con.execute(text("ALTER TABLE dim_date ADD PRIMARY KEY (date_key);"))


            con.execute(text("""
                ALTER TABLE fact_order_items 
                ADD CONSTRAINT fk_sales_customer FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
                ADD CONSTRAINT fk_sales_product FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
                ADD CONSTRAINT fk_sales_seller FOREIGN KEY (seller_key) REFERENCES dim_seller(seller_key),
                ADD CONSTRAINT fk_sales_order FOREIGN KEY (order_key) REFERENCES dim_order(order_key),
                ADD CONSTRAINT fk_sales_date FOREIGN KEY (date_key) REFERENCES dim_date(date_key);
            """))


            con.execute(text("""
                ALTER TABLE fact_delivery_performance 
                ADD CONSTRAINT fk_delivery_customer FOREIGN KEY (customer_key) REFERENCES dim_customer(customer_key),
                ADD CONSTRAINT fk_delivery_product FOREIGN KEY (product_key) REFERENCES dim_product(product_key),
                ADD CONSTRAINT fk_delivery_seller FOREIGN KEY (seller_key) REFERENCES dim_seller(seller_key),
                ADD CONSTRAINT fk_delivery_order FOREIGN KEY (order_key) REFERENCES dim_order(order_key),
                ADD CONSTRAINT fk_delivery_date FOREIGN KEY (date_key) REFERENCES dim_date(date_key);
            """))

            

            con.execute(text("CREATE INDEX idx_sales_customer ON fact_order_items(customer_key);"))
            con.execute(text("CREATE INDEX idx_sales_product ON fact_order_items(product_key);"))
            con.execute(text("CREATE INDEX idx_sales_seller ON fact_order_items(seller_key);"))
            con.execute(text("CREATE INDEX idx_sales_order ON fact_order_items(order_key);"))
            con.execute(text("CREATE INDEX idx_sales_date ON fact_order_items(date_key);"))

            con.execute(text("CREATE INDEX idx_deliv_customer ON fact_delivery_performance(customer_key);"))
            con.execute(text("CREATE INDEX idx_deliv_product ON fact_delivery_performance(product_key);"))
            con.execute(text("CREATE INDEX idx_deliv_seller ON fact_delivery_performance(seller_key);"))
            con.execute(text("CREATE INDEX idx_deliv_order ON fact_delivery_performance(order_key);"))
            con.execute(text("CREATE INDEX idx_deliv_date ON fact_delivery_performance(date_key);"))
            
            con.execute(text("CREATE INDEX idx_delivery_days ON fact_delivery_performance(delivery_days);"))
            
            con.commit()
            print("تم بناء مستودع البيانات")

    except Exception as e:
        print(f"خطا: {e}")

load_to_postgres(all_dimensions, fact_order_items, fact_delivery, dim_date, conn_string)

تم رفع البيانات
تم بناء مستودع البيانات

-------------------------------------

# المرحلة الثاثة عشرة: طبقة التقارير

# السؤال الأول: كيف تتجه المبيعات بمرور الوقت؟

هذا التقرير مخصص لمديري المبيعات لمراقبة نمو الشركة وتحديد المواسم الشرائية يعتمد التحليل على الربط بين جدول حقائق المبيعات وجدول أبعاد الزمن

**الهدف:**
* اكتشاف الأشهر ذات الأداء العالي
* مقارنة المبيعات بين السنوات والأرباع السنوية

In [16]:
query_1 = """
    SELECT d.year, d.month, SUM(f.sales_amount) as total_revenue
    FROM fact_order_items f
    JOIN dim_date d ON f.date_key = d.date_key
    GROUP BY d.year, d.month
    ORDER BY d.year, d.month
"""
engine = create_engine(conn_string)
df_sales_trends = pd.read_sql(query_1, engine)
print("مخرجات اتجاه المبيعات:")
display(df_sales_trends.head())

مخرجات اتجاه المبيعات:

   year  month  total_revenue
0  2016      9         267.36
1  2016     10       49507.66
2  2016     12          10.90
3  2017      1      120312.87
4  2017      2      247303.02

# السؤال الثاني: من هم العملاء الأكثر قيمة؟

يساعد هذا التقرير فريق التسويق على تحديد شريحة العملاء الأوفياء لتوجيه حملات العروض الخاصة لهم

**الهدف:**
* ترتيب العملاء حسب إجمالي إنفاقهم
* معرفة التوزيع الجغرافي لأهم العملاء

In [17]:
query_2 = """
    SELECT c.customer_unique_id, c.customer_city, SUM(f.sales_amount) as total_spent
    FROM fact_order_items f
    JOIN dim_customer c ON f.customer_key = c.customer_key
    GROUP BY c.customer_unique_id, c.customer_city
    ORDER BY total_spent DESC
    LIMIT 10
"""
df_top_customers = pd.read_sql(query_2, engine)
print(" قائمة الـ 10 الكبار من العملاء:")
display(df_top_customers)

 قائمة الـ 10 الكبار من العملاء:

                 customer_unique_id   customer_city  total_spent
0  0a0a92112bd4c708ca5fde585afaa872  rio de janeiro      13440.0
1  da122df9eeddfedc1dc1f5349a1a690c        araruama       7388.0
2  763c8b1c9c68a0229c42c9fc6f662b93      vila velha       7160.0
3  dc4802a71eae9be1dd28f5d788ceb526    campo grande       6735.0
4  459bef486812aa25204be022145caa62         vitoria       6729.0
5  ff4159b92c40ebe40454e3e6a7c35ed6         marilia       6499.0
6  4007669dec559734d6f53e029e360987     divinopolis       5934.6
7  eebb5dda148d3893cdaf5b5ca3040ccb            maua       4690.0
8  5d0a2980b292d049061542014e8960bf         goiania       4599.9
9  48e1ac109decbb87765a3eade6854098     joao pessoa       4590.0

# السؤال الثالث : التحليل الشامل لمسببات تأخير التوصيل 

هذا التقرير هو المختبر الخاص بنا حيث سنقوم بفحص كافة الفرضيات الممكنة التي قد تؤدي للتأخير

**المحاور التي سنحللها في آن واحد:**
1. **المسؤولية التشغيلية:** هل التأخير ناتج عن بطء البائع في التجهيز أم بطء شركة الشحن في الطريق؟
2. **الخصائص الفيزيائية:** هل وزن المنتج وحجمه يجعلان شحنه أصعب وأبطأ؟
3. **الجغرافيا والمسافة:** هل المسار بين ولاية البائع وولاية العميل هو العائق الأساسي؟

In [18]:
query_3_comprehensive = """
    SELECT 
        s.seller_state AS from_state, 
        c.customer_state AS to_state,
        
        CASE 
            WHEN p.product_weight_g < 2000 THEN 'Light (<2kg)'
            WHEN p.product_weight_g BETWEEN 2000 AND 10000 THEN 'Medium (2-10kg)'
            ELSE 'Heavy (>10kg)'
        END AS weight_category,
        
        AVG(f.approval_delay) AS avg_internal_processing, 
        AVG(f.carrier_delay) AS avg_seller_prep_time,    
        AVG(f.delivery_days - f.carrier_delay) AS avg_transit_time, 
        AVG(f.delivery_days) AS total_delivery_time,
        AVG(f.late_days) AS avg_actual_delay
        
    FROM fact_delivery_performance f
    JOIN dim_seller s ON f.seller_key = s.seller_key
    JOIN dim_customer c ON f.customer_key = c.customer_key
    JOIN dim_product p ON f.product_key = p.product_key
    
    GROUP BY from_state, to_state, weight_category
    HAVING COUNT(*) > 20 
    ORDER BY avg_actual_delay DESC
    LIMIT 20
"""

df_comprehensive_delivery = pd.read_sql(query_3_comprehensive, engine)
print(" التقرير الشامل لمسببات التأخير (جغرافيا + وزن + مراحل تشغيلية):")
display(df_comprehensive_delivery)

 التقرير الشامل لمسببات التأخير (جغرافيا + وزن + مراحل تشغيلية):

,from_state,to_state,weight_category,avg_internal_processing,avg_seller_prep_time,avg_transit_time,total_delivery_time,avg_actual_delay
0,SP,RR,Light (<2kg),0.208333,4.041667,29.500000,33.541667,7.166667
1,SP,PI,Heavy (>10kg),0.076923,3.846154,24.692308,28.538462,6.923077
2,SP,AP,Light (<2kg),0.590909,1.681818,28.727273,30.409091,6.568182
3,SC,BA,Medium (2-10kg),0.115385,1.692308,22.384615,24.076923,6.538462
4,RJ,CE,Light (<2kg),0.541667,2.270833,24.562500,26.833333,6.000000
5,PR,AL,Light (<2kg),0.181818,4.545455,25.424242,29.969697,5.121212
6,MG,ES,Medium (2-10kg),0.222222,1.800000,15.777778,17.577778,4.711111
7,PR,CE,Light (<2kg),0.425926,1.777778,23.240741,25.018519,4.388889
8,MG,PA,Light (<2kg),0.222222,3.000000,24.634921,27.634921,4.063492
9,SP,PI,Medium (2-10kg),0.187500,2.712500,18.737500,21.450000,3.375000
10,SC,RJ,Heavy (>10kg),0.325000,3.575000,17.850000,21.425000,3.175000
11,SC,MG,Heavy (>10kg),0.195652,5.173913,15.956522,21.130435,2.869565
12,SP,SE,Light (<2kg),0.295455,2.619318,18.443182,21.062500,2.806818
13,MG,PB,Light (<2kg),0.512195,2.414634,19.585366,22.000000,2.756098
14,SP,CE,Medium (2-10kg),0.254335,2.976879,18.878613,21.855491,2.670520
15,PR,BA,Medium (2-10kg),0.404255,4.936170,15.638298,20.574468,2.468085
16,PR,BA,Light (<2kg),0.429907,2.336449,19.224299,21.560748,2.345794
17,MG,BA,Medium (2-10kg),0.376068,1.897436,17.666667,19.564103,2.341880
18,PR,RJ,Medium (2-10kg),0.185484,2.629032,14.951613,17.580645,2.274194
19,SP,BA,Heavy (>10kg),0.244094,6.228346,17.850394,24.078740,2.251969

# السؤال الرابع: ما هي المنتجات والفئات التي تدفع الإيرادات؟ 

يساعد هذا التقرير مديري المشتريات والمخازن على معرفة المنتجات التي تشكل الحصة الأكبر من دخل الشركة لضمان توفرها دائماً

**الهدف:**
* تحديد الفئات الأكثر ربحية
* موازنة حجم المبيعات الكمية مع القيمة المالية الإيراد

In [19]:
query_4 = """
    SELECT p.product_category_name_english as category, 
            SUM(f.sales_amount) as total_revenue,
            SUM(f.quantity) as total_units_sold
    FROM fact_order_items f
    JOIN dim_product p ON f.product_key = p.product_key
    GROUP BY category
    ORDER BY total_revenue DESC
    LIMIT 10
"""
df_revenue_drivers = pd.read_sql(query_4, engine)
print(" أفضل الفئات من حيث حجم الإيرادات:")
display(df_revenue_drivers)

 أفضل الفئات من حيث حجم الإيرادات:

                category  total_revenue  total_units_sold
0          health_beauty     1258681.34           11081.0
1          watches_gifts     1205005.68            6594.0
2         bed_bath_table     1036988.68           13665.0
3         sports_leisure      988048.97            9932.0
4  computers_accessories      911954.32            9874.0
5        furniture_decor      729762.49           11540.0
6             cool_stuff      635290.85            4077.0
7             housewares      632248.66            9051.0
8                   auto      592720.11            4881.0
9           garden_tools      485256.46            5874.0

# تم إنشاء الداتا وير هاوس مع الإجابه علئ كافة اسئله البزنسس شكرا

--------------------------------